name: PR Approval Request Send To Telegram

on:
  pull_request:
    types:
      - opened

jobs:
  send-approval-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '17'

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn -B clean install

      - name: Send approval request to Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=🚀 Pull Request opened! Please review and approve: ${{ github.event.pull_request.html_url }}" \
            -d "parse_mode=Markdown"
