name: PR Approval Request Send To Telegram

on:
  pull_request:
    types:
      - opened

jobs:
  send-approval-request:
    runs-on: ubuntu-latest
    if: ${{ github.event.opened.mergeable }} == "false"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send approval request to Telegram
        run: |
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
              -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
              -d "text=🚀 Pull Request opened! Please review and approve: ${{ github.event.pull_request.html_url }}" \
              -d "parse_mode=Markdown"
